import { Sparkles, X, Loader2 } from 'lucide-react'

function Section({ title, children }) {
  return (
    <div className="space-y-1.5">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{title}</h3>
      {children}
    </div>
  )
}

const ENERGY_LABEL = { low: 'Low', medium: 'Medium', high: 'High', varied: 'Varied' }

export default function AnalysisPanel({ playlistName, state, onClose }) {
  const { status, data, error } = state

  return (
    <aside className="flex w-[340px] shrink-0 flex-col border-l border-border bg-sidebar/40">
      <div className="flex shrink-0 items-center gap-2 border-b border-border px-4 py-3">
        <Sparkles className="size-4 text-primary" />
        <h2 className="flex-1 truncate text-sm font-semibold">AI Analysis</h2>
        <button
          type="button"
          onClick={onClose}
          className="rounded-md p-1 text-muted-foreground hover:bg-accent hover:text-foreground"
          aria-label="Close analysis"
        >
          <X className="size-4" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4">
        {status === 'loading' && (
          <div className="flex flex-col items-center gap-3 pt-16 text-sm text-muted-foreground">
            <Loader2 className="size-6 animate-spin" />
            <p>Analyzing “{playlistName}”…</p>
          </div>
        )}

        {status === 'error' && (
          <div className="rounded-md border-l-2 border-destructive bg-card px-3 py-2.5 text-[13px] leading-relaxed text-muted-foreground">
            {error}
          </div>
        )}

        {status === 'done' && data && (
          <div className="space-y-5">
            <Section title="Vibe">
              <p className="text-sm leading-relaxed text-foreground/90">{data.analysis.vibe}</p>
            </Section>

            <Section title="Genres">
              <div className="flex flex-wrap gap-1.5">
                {data.analysis.genres.map((g) => (
                  <span
                    key={g}
                    className="rounded-full border border-border bg-card/60 px-2.5 py-1 text-xs text-foreground/90"
                  >
                    {g}
                  </span>
                ))}
              </div>
            </Section>

            <div className="flex gap-3">
              <Section title="Energy">
                <p className="text-sm font-medium text-foreground/90">
                  {ENERGY_LABEL[data.analysis.energy] ?? data.analysis.energy}
                </p>
              </Section>
              {data.stats.bpm && (
                <Section title="BPM">
                  <p className="text-sm font-medium tabular-nums text-foreground/90">
                    {data.stats.bpm.min}–{data.stats.bpm.max}{' '}
                    <span className="text-muted-foreground">(avg {data.stats.bpm.avg})</span>
                  </p>
                </Section>
              )}
            </div>

            <Section title="Best for">
              <ul className="space-y-1 text-sm text-foreground/90">
                {data.analysis.best_for.map((b) => (
                  <li key={b} className="flex gap-2">
                    <span className="text-muted-foreground">•</span>
                    <span>{b}</span>
                  </li>
                ))}
              </ul>
            </Section>

            <Section title="Notable tracks">
              <ul className="space-y-1 text-sm text-foreground/90">
                {data.analysis.notable_tracks.map((t) => (
                  <li key={t}>{t}</li>
                ))}
              </ul>
            </Section>

            <p className="pt-2 text-[11px] text-muted-foreground/70">
              Generated by Claude from {data.stats.track_count} tracks.
            </p>
          </div>
        )}
      </div>
    </aside>
  )
}
